name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Установка зависимостей
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск тестов
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Вход в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Сборка и пуш Docker-образа
        run: |
          docker build -t myusername/sales_trading_app .
          docker tag myusername/sales_trading_app myusername/sales_trading_app:latest
          docker push myusername/sales_trading_app:latest

      - name: Деплой на сервер
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull myusername/sales_trading_app:latest
            docker stop django_app || true
            docker rm django_app || true
            docker run -d --name django_app -p 8000:8000 myusername/sales_trading_app:latest
